version: "3.9"
services:
  shop:
    build: .
    environment:
      BOT_TOKEN:
      API_ID: 9840531
      API_HASH: 2ac10377616df23907e134df14bdf08b
      CHANNELS: -1001761985553
      ADMINS: 960432019
      PICS: https://telegra.ph/file/fb3280910313f91b8c1d7.jpg
      LOG_CHANNEL: -1001761985553
      DATABASE_URI: mongodb+srv://Hacker999:selvan868@cluster0.z27ur.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
      DATABASE_NAME: Hacker999
      COLLECTION_NAME: Telegram_files
      IMDB: True
